### ISSUE TITLE
Chef gem install fails

### ISSUE THREAD

**Issue by poloka** [coderanger/knife-solve#4]
Followed the readme instructions on installing knife-solve

```
chef gem install knife-solve
```

But upon installation is noted that my $HOME/.chefdk/gem/ruby/2.1.0/bin is not in my PATH.  I added it to my path but in reviewing the location, no bin exists at that location.  Am I missing something? 

I'm running with:
Chef Development Kit Version: 0.10.0

**Comment by coderanger** [comment]
This gem doesn't ship a binary, it is a plugin for knife which comes with Chef. Probably try upgrading to the latest ChefDK and check if you are using the `knife rehash` plugin config and if so run `knife rehash` again to regenerate it.

**Comment by poloka** [comment]
Upgraded to latest chefdk:
Chef Development Kit Version: 0.12.0

I am not using caching and made sure there was no plugin_manifest.json in my .chef folder.

**Comment by coderanger** [comment]
What issue are you seeing?

**Comment by poloka** [comment]
Sorry, should have been clear about that.  Upon installing the plugin, it does not appear to be accessible.

```
FATAL: Cannot find subcommand for: 'solve -n <node>'
```

**Comment by coderanger** [comment]
Make sure you are using the `knife` from inside ChefDK? Try `chef exec knife solve --help` perhaps?

**Comment by poloka** [comment]
That worked.  Looks like knife is being executed by bundler rather than by chef:

```
╰─➤  which knife                                                                                                                         1 ↵
knife: aliased to bundled_knife
╰─➤  which bundled_knife
bundled_knife () {
    _run-with-bundler knife $@
}
╰─➤  which _run-with-bundler
_run-with-bundler () {
    if _bundler-installed && _within-bundled-project
    then
        if _binstubbed $1
        then
            ./bin/$@
        else
            bundle exec $@
        fi
    else
        $@
    fi
}
```

**Comment by coderanger** [comment]
Then you probably need to either add them gem to your gemfile is one is present or otherwise install the gem into the right Ruby environment.
